# Knowledge Base Configuration
# Wiki Vault RAG System

knowledge_base:
  name: "Personal Wiki Knowledge Base"
  creator: "Benjamin Merritt"
  topic: "Claude Code, Content Creation & Technical Knowledge"
  description: "Personal knowledge wiki with guides, references, and documentation"
  
  # Response style
  personality: "technical, precise, and helpful"
  example_phrases:
    - "Based on the knowledge base documentation..."
    - "According to the guide on..."
    - "The wiki contains information about..."

data_sources:
  # Wiki vault uses markdown files only
  use_source_notes: true      # Your wiki markdown files
  use_transcripts: false      # No video transcripts
  prefer_transcripts: false   # Not applicable
  
  # Path to your vault content
  source_notes_dir: "md-vault"
  
  # Format settings for wiki
  require_sections: false     # Wiki files have various formats
  flexible_metadata: true     # Accept any frontmatter
  
embeddings:
  # Use OpenAI for best quality
  provider: "openai"
  model: "text-embedding-3-large"
  dimensions: 3072
  
  # Fallback if no API key
  fallback_provider: "local"
  fallback_model: "all-MiniLM-L6-v2"
  
  # Processing
  batch_size: 100
  show_progress: true

chunking:
  # For wiki notes
  notes_chunk_size: 1500      # Larger chunks for documentation
  notes_chunk_overlap: 300    # More overlap for context
  
  # Smart chunking for wiki structure
  preserve_sections: true     # Keep headers intact
  min_chunk_size: 200
  max_chunk_size: 3000        # Allow larger chunks for guides

search:
  # Retrieval settings
  top_k_initial: 20
  top_k_final: 10
  min_relevance_score: 0.5    # Lower threshold for broader matches
  
  # Search features
  enable_hybrid: true         # Good for technical content
  enable_mmr: true           # Diversity in results

generation:
  # Optional - only if using OpenAI for Q&A
  provider: "openai"
  model: "gpt-4o-mini"
  temperature: 0.2           # Lower temp for technical accuracy
  max_tokens: 2000
  
  # System prompt for wiki content
  system_prompt: |
    You are an AI assistant with access to a personal knowledge wiki.
    The wiki contains technical documentation, guides, and reference materials.
    Provide accurate answers based on the wiki content.
    Always cite the specific document or section when possible.
    Focus on technical accuracy and practical application.

chroma:
  persist_directory: "chroma_db"
  collection_prefix: "wiki"    # Collections: wiki_content, wiki_concepts, wiki_metadata
  
  collections:
    content: "content"    # Main document chunks (will be wiki_content)
    concepts: "concepts"  # Key concepts and terms (will be wiki_concepts)
    metadata: "metadata"  # Document metadata (will be wiki_metadata)

logging:
  level: "INFO"
  file: "wiki_rag.log"

# Disable MCP for now
mcp:
  enabled: false

analytics:
  track_queries: true
  track_performance: true
  export_metrics: false