# Agent Vault Knowledge Base Configuration (Profile)

knowledge_base:
  name: "Agent Vault KB"
  creator: "Benjamin Merritt"
  topic: "Agent systems"
  description: "Agent-vault-old converted into a searchable RAG knowledge base"
  personality: "technical, precise, and helpful"

data_sources:
  use_source_notes: true
  use_transcripts: false
  prefer_transcripts: false
  source_notes_dir: "/Users/benjaminmerritt/agent-vault-old"

embeddings:
  # Use local embeddings for fast, offline indexing (recommended for large vaults)
  provider: "local"
  fallback_model: "all-MiniLM-L6-v2"
  # You can switch to OpenAI later by setting provider: openai and adding an API key
  batch_size: 100
  show_progress: true

chunking:
  notes_chunk_size: 1500
  notes_chunk_overlap: 300
  preserve_sections: true
  min_chunk_size: 200
  max_chunk_size: 3000

search:
  top_k_initial: 20
  top_k_final: 12
  min_relevance_score: 0.5
  enable_hybrid: true
  enable_mmr: true

generation:
  provider: "openai"
  model: "gpt-4o-mini"
  temperature: 0.2
  max_tokens: 2500
  system_prompt: |
    You are an AI assistant with access to a personal knowledge base.
    Provide accurate answers grounded in the provided context.
    Cite sources inline when useful and include a final Sources section.

chroma:
  persist_directory: "/Users/benjaminmerritt/agent-vault-old/chroma_db"
  collection_prefix: "agent"
  collections:
    content: "content"
    concepts: "concepts"
    metadata: "metadata"

logging:
  level: "INFO"
  file: "wiki_rag.log"

mcp:
  enabled: false

analytics:
  track_queries: true
  track_performance: true
  export_metrics: false

