# Hormozi Transcripts KB — Deployment Profile

knowledge_base:
  name: "Hormozi Transcripts KB"
  creator: "Benjamin Merritt"
  topic: "Hormozi content transcripts"
  description: "Searchable RAG over raw Markdown transcripts"
  personality: "technical, precise, and helpful"

data_sources:
  use_source_notes: false
  use_transcripts: true
  prefer_transcripts: true
  transcripts_dir: "/app/data/transcripts"
  source_notes_dir: "/app/data/notes"

embeddings:
  provider: "local"
  fallback_model: "all-MiniLM-L6-v2"
  batch_size: 256
  show_progress: true

chunking:
  notes_chunk_size: 1800
  notes_chunk_overlap: 200
  preserve_sections: true
  min_chunk_size: 200
  max_chunk_size: 3000
  transcript_chunk_minutes: 3
  transcript_overlap_seconds: 30

search:
  top_k_initial: 30
  top_k_final: 15
  min_relevance_score: 0.5
  enable_hybrid: true
  enable_mmr: true

generation:
  provider: "openai"
  model: "gpt-4o-mini"
  temperature: 0.2
  max_tokens: 2600
  system_prompt: |
    You are an AI assistant with access to Hormozi transcripts.
    Provide deep, synthesized, actionable answers with clear steps.
    Always include a final Sources section with titles + links.

chroma:
  persist_directory: "/data/chroma_db"
  collection_prefix: "hormozi"
  collections:
    content: "content"
    concepts: "concepts"
    metadata: "metadata"

logging:
  level: "INFO"
  file: "hormozi_rag.log"

mcp:
  enabled: false

analytics:
  track_queries: true
  track_performance: true
  export_metrics: false

