# Jay Transcripts KB (Ask-Jay)

knowledge_base:
  name: "Ask-Jay Transcripts KB"
  creator: "Benjamin Merritt"
  topic: "Jay calls and video transcripts"
  description: "Searchable RAG over raw .txt/.md transcripts for Ask-Jay"
  personality: "direct, specific, and helpful"

data_sources:
  use_source_notes: false
  use_transcripts: true
  prefer_transcripts: true
  transcripts_dir: "/Users/benjaminmerritt/raw-transcripts/PMM/pmm-transcripts"
  source_notes_dir: "md-vault"  # ignored when use_source_notes=false

embeddings:
  provider: "local"
  fallback_model: "all-MiniLM-L6-v2"
  batch_size: 256
  show_progress: true

chunking:
  notes_chunk_size: 1800
  notes_chunk_overlap: 200
  preserve_sections: true
  min_chunk_size: 200
  max_chunk_size: 3000
  transcript_chunk_minutes: 4
  transcript_overlap_seconds: 25

search:
  top_k_initial: 40
  top_k_final: 15
  min_relevance_score: 0.5
  enable_hybrid: true
  enable_mmr: true

generation:
  provider: "openai"
  model: "gpt-4o-mini"
  temperature: 0.2
  max_tokens: 2600
  system_prompt: |
    You are an AI assistant answering questions using only the provided transcripts.
    Provide deep, synthesized, actionable answers with clear steps and a Sources list (titles + links).

chroma:
  persist_directory: "/Users/benjaminmerritt/raw-transcripts/PMM/chroma_db"
  collection_prefix: "jay"
  collections:
    content: "content"
    concepts: "concepts"
    metadata: "metadata"

logging:
  level: "INFO"
  file: "jay_rag.log"

mcp:
  enabled: false

analytics:
  track_queries: true
  track_performance: true
  export_metrics: false

